name: AFKMania
version: '${project.version}'
main: me.pizzalover.afkmania.Main
api-version: '1.20'
folia-supported: true


softdepend:
  - DecentHolograms
  - WorldGuard

commands:
  afkmania:
    description: Main command for AFKMania
    usage: /<command> [reload]
    permission: afkmania.reload

permissions:
  afkmania.reload:
    description: Allows the player to reload the plugin
    default: op
